apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookie
  labels:
    app: cookie-webpage-deployment
    tier: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cookie-webpage-deployment
  template:
    metadata:
      labels:
        app: cookie-webpage-deployment
        tier: front-end
    spec:
      containers:
        - name: cookie-webpage-deploy-container
          image: jendaredocker/jendarey-cookie-company-webpage-main:latest
          ports:
            - containerPort: 8080
