apiVersion: v1
kind: Service
metadata:
  name: cookie-service
  labels:
    app: cookie-webpage-deployment
    tier: front-end
spec:
  type: LoadBalancer  
  selector:
    app: cookie-webpage-deployment
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8080
